# This template is used to create routing rules for Traefik
# References: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
#             https://doc.traefik.io/traefik/routing/routers
#             https://doc.traefik.io/traefik/routing/services

[http.routers]

  [http.routers.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 714
    rule = "PathPrefix(`/jfconfig/`)"
    middlewares = ["jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip","jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-add"]

  [http.routers.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-external]
    entryPoints = ["external"]
    service = "local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 714
    rule = "PathPrefix(`/jfconfig/`)"
    middlewares = ["jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip","jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-add","hotPath","mtls"]

  [http.routers.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 735
    rule = "PathPrefix(`/com.jfrog.access.v1.config.`)"

  [http.routers.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule0-external]
    entryPoints = ["external"]
    service = "local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 735
    rule = "PathPrefix(`/com.jfrog.access.v1.config.`)"
    middlewares = ["hotPath","mtls"]

  [http.routers.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule1-internal]
    entryPoints = ["internal"]
    service = "local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 725
    rule = "PathPrefix(`/com.jfrog.jfconfig.`)"

  [http.routers.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule1-external]
    entryPoints = ["external"]
    service = "local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 725
    rule = "PathPrefix(`/com.jfrog.jfconfig.`)"
    middlewares = ["hotPath","mtls"]

[http.services]

  [http.services.local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer.servers]]
      url = "http://localhost:8010"

  [http.services.local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-1.loadBalancer.servers]]
      url = "h2c://localhost:8011"

[http.middlewares]

  [http.middlewares.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-add.addPrefix]
    prefix = "/jfconfig"

  [http.middlewares.jfcfg_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip.stripPrefix]
    prefixes = ["/jfconfig/"]
