# This template is used to create routing rules for Traefik
# References: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
#             https://doc.traefik.io/traefik/routing/routers
#             https://doc.traefik.io/traefik/routing/services

[http.routers]

  [http.routers.jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 715
    rule = "PathPrefix(`/jfconnect/`)"
    middlewares = ["jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip"]

  [http.routers.jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-external]
    entryPoints = ["external"]
    service = "local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 715
    rule = "PathPrefix(`/jfconnect/`)"
    middlewares = ["jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip","hotPath","mtls"]

  [http.routers.jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 726
    rule = "PathPrefix(`/com.jfrog.jfconnect.`)"

  [http.routers.jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule0-external]
    entryPoints = ["external"]
    service = "local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 726
    rule = "PathPrefix(`/com.jfrog.jfconnect.`)"
    middlewares = ["hotPath","mtls"]

[http.services]

  [http.services.local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer.servers]]
      url = "http://localhost:8030"

  [http.services.local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-1.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-1.loadBalancer.servers]]
      url = "h2c://localhost:8035"

[http.middlewares]

  [http.middlewares.jfcon_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip.stripPrefix]
    prefixes = ["/jfconnect/"]
