# This template is used to create routing rules for Traefik
# References: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
#             https://doc.traefik.io/traefik/routing/routers
#             https://doc.traefik.io/traefik/routing/services

[http.routers]

  [http.routers.jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 714
    rule = "PathPrefix(`/evidence/`)"
    middlewares = ["jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip"]

  [http.routers.jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-external]
    entryPoints = ["external"]
    service = "local-jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 714
    rule = "PathPrefix(`/evidence/`)"
    middlewares = ["jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip","hotPath","mtls"]

[http.services]

  [http.services.local-jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer.servers]]
      url = "http://localhost:8051"

[http.middlewares]

  [http.middlewares.jfevd_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip.stripPrefix]
    prefixes = ["/evidence/"]
