# This template is used to create routing rules for Traefik
# References: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
#             https://doc.traefik.io/traefik/routing/routers
#             https://doc.traefik.io/traefik/routing/services

[http.routers]

  [http.routers.jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 711
    rule = "PathPrefix(`/event/`)"
    middlewares = ["jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip"]

  [http.routers.jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0-rule0-external]
    entryPoints = ["external"]
    service = "local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0"
    priority = 711
    rule = "PathPrefix(`/event/`)"
    middlewares = ["jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip","hotPath","mtls"]

  [http.routers.jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 722
    rule = "PathPrefix(`/com.jfrog.event.`)"

  [http.routers.jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-1-rule0-external]
    entryPoints = ["external"]
    service = "local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-1"
    priority = 722
    rule = "PathPrefix(`/com.jfrog.event.`)"
    middlewares = ["hotPath","mtls"]

[http.services]

  [http.services.local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0.loadBalancer.servers]]
      url = "http://localhost:8061"

  [http.services.local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-1.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-1.loadBalancer.servers]]
      url = "h2c://localhost:8062"

[http.middlewares]

  [http.middlewares.jfevt_01k3dadp7e688m028tztv9160g-artifactory-0-0-0-strip.stripPrefix]
    prefixes = ["/event/"]
