# This template is used to create routing rules for Traefik
# References: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
#             https://doc.traefik.io/traefik/routing/routers
#             https://doc.traefik.io/traefik/routing/services

[http.routers]

  [http.routers.jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0-rule0-internal]
    entryPoints = ["internal"]
    service = "local-jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0"
    priority = 719
    rule = "PathPrefix(`/observability/`)"
    middlewares = ["jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0-0-strip"]

  [http.routers.jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0-rule0-external]
    entryPoints = ["external"]
    service = "local-jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0"
    priority = 719
    rule = "PathPrefix(`/observability/`)"
    middlewares = ["jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0-0-strip","hotPath","mtls"]

[http.services]

  [http.services.local-jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0.loadBalancer]
    passHostHeader = false

    [[http.services.local-jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0.loadBalancer.servers]]
      url = "http://localhost:8036"

[http.middlewares]

  [http.middlewares.jfob_01k3dadv4an03k1v3xy8fe0ccm-artifactory-0-0-0-strip.stripPrefix]
    prefixes = ["/observability/"]
